### PR TITLE
[#729] Make auth header compliant with rfc6750 (Bearer auth)

### LINKED ISSUE #729: RFC650 Compliance of API Bearer JWT Authentication
Authentication for the HTTP API currently works as follows, but is undocumented (https://docs.airy.co/api/http#authentication):

```
     POST /resource HTTP/1.1
     Host: server.example.com
     Authorization: SOME_VALID_JWT
```

According to the RFC6750 standard (https://tools.ietf.org/html/rfc6750#section-2.1) the client should us the "Bearer" authentication scheme to transmit the access token as follows:

```
     POST /resource HTTP/1.1
     Host: server.example.com
     Authorization: Bearer SOME_VALID_JWT
```

The documentation should also be amended accordingly to tell users how to authenticate.

### PR DESCRIPTION
**Pull request by chrismatix**
fixes #729

### CODE REVIEW

**Review by paulodiniz — DISMISSED** [review]

**Comment by pascal-airy** [comment]
Could you also add `Bearer` to the curl examples in https://github.com/airyhq/airy/blob/develop/docs/docs/getting-started/quickstart.md so we don't break the docs 🙌

**Review by lucapette — DISMISSED** [review]
:shipit:

**Review by pascal-airy — DISMISSED** [review]
👍

**Review by pascal-airy — APPROVED** [review]
purrfection

**Review by lucapette — APPROVED** [review]
:shipit:

**Pull request merged**
