### PR TITLE
Fix/1413 expand chat plugin by default

### LINKED ISSUE #1413: Expand Chat Plugin by default
Currently, the chat plugin is collapsed/minimized by default. We should create a custom behavior for returning to conversations so that the chat plugin is expanded by default.

For example: when a contact clicks on the link provided to resume the conversation, it would be ideal if the plugin would already be open and ready, so that the contact does not have to click once again to open the chat and begin typing.

### PR DESCRIPTION
**Pull request by AudreyKj**
closes #1413 

The chat is expanded when there is a resume token, it is hidden when there is no resume token.

### CODE REVIEW

**Comment by bitboxer** [comment]
🤔  Then it is always open as soon as I once talked to someone, right? Might be a bit annoying to go back to a page 3 months later and see that old message pop up .

**Comment by AudreyKj** [comment]
@bitboxer yeah the chat will appear as open as soon as the conversation started. @lizhutter what do you think?

**Comment by bitboxer** [comment]
Asking because there is no way for a customer to end the chat and this means we can't not open the popup.

**Comment by lizhutter** [comment]
@AudreyKj @bitboxer There is currently a ticket for end chat (https://github.com/airyhq/airy/issues/929) that needs to be discussed, but it will help with this situation once it's out of discussion and has been worked on.

**Pull request merged**
